name: Publish Articles

on:
  push:
    branches: ['main']
    paths: ['articles/*.md']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Dev.to
        uses: protiumx/blogpub@v0.6.0
        with:
          gh_token: ${{ github.token }}
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          articles_folder: articles
